import numpy as np
import matplotlib.pyplot as pl
a1=np.arange(1,20,1.25,np.float32)
a2=np.log(a1)
a3=np.cos(a1)
print(a1,a2,a3,sep='\n\n\n')
pl.xlabel('Random Values>')
pl.ylabel('Logarithmic Values>')
pl.xlim(25,-2)
pl.xticks([10,6,2,-2])
pl.ylim(-2,5)
pl.yticks([-1,])
pl.plot(a1,a2,'kd',linewidth=2,markersize=5,markeredgecolor='b',label='graph1')
pl.plot(a1,a3,'mo',markeredgecolor='k',linewidth=2,linestyle='dashdot',label='graph2')
pl.legend(loc=1)
pl.savefig("graphsav1.pdf")
pl.show()
pl.plot(a1,a2)
pl.savefig("graphsav1.pdf")
pl.show()