import numpy as np
import matplotlib.pyplot as pl
def s():
    pl.show()
a=np.array([1,2,3,4])
b=np.array([2,4,6,8])
c=np.array([1,4,9,16])
pl.xlabel("x axis>")
pl.ylabel("y axis>")
pl.barh(a,b,height=0.2,color=['k','b','m','c'])
pl.barh(a+0.2,c,height=0.2,color='g')
s()
pl.bar(a,b,width=0.2,color=['k','b','m','c'])
pl.bar(a+0.2,c,width=0.2,color='g')
s()
pl.axis("equal")
pl.pie(a,labels=a,autopct="%1.1f%%")
s()
pl.title("Mera papa ka naam bhai chart h")
pl.pie(b,labels=b,autopct="%1.1f%%")
s()
pl.title("Mera naam pie chart h")
pl.pie(c,labels=c,autopct="%2.3i%%",colors=['k','m'],explode=[0.2,0.2,0.2,0.2])
s()